USE Luvpet_Prd;
DROP TABLE IF EXISTS `Brand`;
CREATE TABLE `Brand` (
	`BrandID` INT NOT NULL AUTO_INCREMENT,
	`BrandCN` NVARCHAR(15) NOT NULL,
	`BrandEN` VARCHAR(25) NOT NULL,
	`InUser` VARCHAR(15) NOT NULL DEFAULT 'sys',
	`InDate` TIMESTAMP NOT NULL DEFAULT current_timestamp,
	`LastEditUser` VARCHAR(15) NOT NULL DEFAULT 'sys',
	`LastEditDate` TIMESTAMP NOT NULL DEFAULT current_timestamp ON UPDATE current_timestamp,
	PRIMARY KEY (`BrandID`)
) ENGINE = INNODB DEFAULT CHAR SET = UTF8;
