DROP TABLE IF EXISTS `Category`;
CREATE TABLE `Category` (
	`CategoryID` INT NOT NULL AUTO_INCREMENT,
	`CategoryCN` NVARCHAR(15) NOT NULL ,
	`CategoryEN` VARCHAR(25) NOT NULL ,
	`InUser` VARCHAR(15) NOT NULL DEFAULT 'sys',
	`InDate` TIMESTAMP NOT NULL DEFAULT current_timestamp,
	`LastEditUser` VARCHAR(15) NOT NULL DEFAULT 'sys',
	`LastEditDate` TIMESTAMP NOT NULL DEFAULT current_timestamp ON UPDATE current_timestamp,
	PRIMARY KEY (`CategoryID`)
) ENGINE = INNODB DEFAULT CHAR SET = UTF8;
