DROP TABLE IF EXISTS `Country`;
CREATE TABLE `Country` (
	`CountryID` INT NOT NULL AUTO_INCREMENT,
	`CountryNameCN` NVARCHAR(15) NOT NULL ,
	`CountryNameEN` VARCHAR(25) NOT NULL ,
	`InUser` VARCHAR(15) NOT NULL DEFAULT 'sys',
	`InDate` TIMESTAMP NOT NULL DEFAULT current_timestamp,
	`LastEditUser` VARCHAR(15) NOT NULL DEFAULT 'sys',
	`LastEditDate` TIMESTAMP NOT NULL DEFAULT current_timestamp ON UPDATE current_timestamp,
	PRIMARY KEY (`CountryID`)
) ENGINE = INNODB DEFAULT CHAR SET = UTF8;
